package frc.robot.commands.autonomous.auto_scripts;

import edu.wpi.first.wpilibj2.command.SequentialCommandGroup;
import frc.robot.commands.autonomous.auto_commands.Drivetrain_GyroStrafe;
import frc.robot.commands.autonomous.auto_commands.Drivetrain_GyroStraight;
import frc.robot.commands.autonomous.auto_commands.Drivetrain_GyroTurn;

public class StrafeFullTest extends SequentialCommandGroup {

  public StrafeFullTest() {
    // Generated by Tobin's Auto Coder

    addCommands(new Drivetrain_GyroStrafe(1, 0.3));
    addCommands(new Drivetrain_GyroTurn(45));
    addCommands(new Drivetrain_GyroStraight(1, -0.3));
    addCommands(new Drivetrain_GyroTurn(-45));
    addCommands(new Drivetrain_GyroStraight(0.5, -0.3));
    addCommands(new Drivetrain_GyroStrafe(0.5, -0.3));
  }
}